/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.87
 * Generated at: 2024-06-20 07:23:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class list_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1718612358475L));
    _jspx_dependants.put("jar:file:/C:/lee-class-workspace/springProject/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>Document</title>\r\n");
      out.write("    <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js\"></script>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css\">\r\n");
      out.write("    <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js\"></script>\r\n");
      out.write("    <style>\r\n");
      out.write("        .content {\r\n");
      out.write("            background-color:rgb(247, 245, 245);\r\n");
      out.write("            width:80%;\r\n");
      out.write("            margin:auto;\r\n");
      out.write("        }\r\n");
      out.write("        .innerOuter {\r\n");
      out.write("            border:1px solid lightgray;\r\n");
      out.write("            width:80%;\r\n");
      out.write("            margin:auto;\r\n");
      out.write("            padding:5% 10%;\r\n");
      out.write("            background-color:white;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #boardList {text-align:center;}\r\n");
      out.write("        #boardList>tbody>tr:hover {cursor:pointer;}\r\n");
      out.write("\r\n");
      out.write("        #pagingArea {width:fit-content; margin:auto;}\r\n");
      out.write("        \r\n");
      out.write("        #searchForm {\r\n");
      out.write("            width:80%;\r\n");
      out.write("            margin:auto;\r\n");
      out.write("        }\r\n");
      out.write("        #searchForm>* {\r\n");
      out.write("            float:left;\r\n");
      out.write("            margin:5px;\r\n");
      out.write("        }\r\n");
      out.write("        .select {width:20%;}\r\n");
      out.write("        .text {width:53%;}\r\n");
      out.write("        .searchBtn {width:20%;}\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    \r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../common/menubar.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div class=\"content\">\r\n");
      out.write("        <br><br>\r\n");
      out.write("        <div class=\"innerOuter\" style=\"padding:5% 10%;\">\r\n");
      out.write("            <h2>게시판</h2>\r\n");
      out.write("            <br>\r\n");
      out.write("            <!-- 로그인 후 상태일 경우만 보여지는 글쓰기 버튼 -->\r\n");
      out.write("            <a class=\"btn btn-secondary\" style=\"float:right;\" href=\"\">글쓰기</a>\r\n");
      out.write("            <br>\r\n");
      out.write("            <br>\r\n");
      out.write("            <table id=\"boardList\" class=\"table table-hover\" align=\"center\">\r\n");
      out.write("                <thead>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <th>글번호</th>\r\n");
      out.write("                        <th>제목</th>\r\n");
      out.write("                        <th>작성자</th>\r\n");
      out.write("                        <th>조회수</th>\r\n");
      out.write("                        <th>작성일</th>\r\n");
      out.write("                        <th>첨부파일</th>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                </thead>\r\n");
      out.write("                <tbody>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td>5</td>\r\n");
      out.write("                        <td>마지막 게시글제목</td>\r\n");
      out.write("                        <td>admin</td>\r\n");
      out.write("                        <td>10</td>\r\n");
      out.write("                        <td>2024-06-10</td>\r\n");
      out.write("                        <td>💌</td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td>4</td>\r\n");
      out.write("                        <td>네번째 게시글제목</td>\r\n");
      out.write("                        <td>admin</td>\r\n");
      out.write("                        <td>10</td>\r\n");
      out.write("                        <td>2024-06-07</td>\r\n");
      out.write("                        <td>💌</td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td>3</td>\r\n");
      out.write("                        <td>세번째 게시글제목</td>\r\n");
      out.write("                        <td>admin</td>\r\n");
      out.write("                        <td>10</td>\r\n");
      out.write("                        <td>2024-06-03</td>\r\n");
      out.write("                        <td></td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td>2</td>\r\n");
      out.write("                        <td>두번째 게시글제목</td>\r\n");
      out.write("                        <td>admin</td>\r\n");
      out.write("                        <td>100</td>\r\n");
      out.write("                        <td>2024-06-01</td>\r\n");
      out.write("                        <td></td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td>1</td>\r\n");
      out.write("                        <td>첫번째 게시글제목</td>\r\n");
      out.write("                        <td>admin</td>\r\n");
      out.write("                        <td>45</td>\r\n");
      out.write("                        <td>2023-12-25</td>\r\n");
      out.write("                        <td>💌</td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                </tbody>\r\n");
      out.write("            </table>\r\n");
      out.write("            <br>\r\n");
      out.write("\r\n");
      out.write("            <div id=\"pagingArea\">\r\n");
      out.write("                <ul class=\"pagination\">\r\n");
      out.write("                    <li class=\"page-item disabled\"><a class=\"page-link\" href=\"#\">이전</a></li>\r\n");
      out.write("                    <li class=\"page-item\"><a class=\"page-link\" href=\"#\">1</a></li>\r\n");
      out.write("                    <li class=\"page-item\"><a class=\"page-link\" href=\"#\">2</a></li>\r\n");
      out.write("                    <li class=\"page-item\"><a class=\"page-link\" href=\"#\">3</a></li>\r\n");
      out.write("                    <li class=\"page-item\"><a class=\"page-link\" href=\"#\">4</a></li>\r\n");
      out.write("                    <li class=\"page-item\"><a class=\"page-link\" href=\"#\">5</a></li>\r\n");
      out.write("                    <li class=\"page-item\"><a class=\"page-link\" href=\"#\">다음</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <br clear=\"both\"><br>\r\n");
      out.write("\r\n");
      out.write("            <form id=\"searchForm\" action=\"\" method=\"get\" align=\"center\">\r\n");
      out.write("                <div class=\"select\">\r\n");
      out.write("                    <select class=\"custom-select\" name=\"condition\">\r\n");
      out.write("                        <option value=\"writer\">작성자</option>\r\n");
      out.write("                        <option value=\"title\">제목</option>\r\n");
      out.write("                        <option value=\"content\">내용</option>\r\n");
      out.write("                    </select>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"text\">\r\n");
      out.write("                    <input type=\"text\" class=\"form-control\" name=\"keyword\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <button type=\"submit\" class=\"searchBtn btn btn-secondary\">검색</button>\r\n");
      out.write("            </form>\r\n");
      out.write("            <br><br>\r\n");
      out.write("        </div>\r\n");
      out.write("        <br><br>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../common/footer.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
